<?php

namespace Api\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return \Cake\Http\Response
     */
    protected function json($data = [])
    {
        $response = $this->response;
        return $response
            ->withType('json')
            ->withStringBody(
                json_encode($data)
            );
    }
}
